"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { ChevronLeft, ChevronRight, Code2, Pause, Play, RotateCcw, Sliders, X } from "lucide-react";
import { Eyebrow } from "@/components/ui/Section";
import { Button, IconButton, Segmented } from "@/components/ui/Controls";
import { DifficultyTag } from "@/components/ui/Tag";
import { CodeBlock } from "@/components/code/CodeBlock";
import { TraceCanvas, TraceRuler } from "./TraceCanvas";
import { SPEEDS, usePlayback } from "./usePlayback";
import { TraceInputError, defaultTraceFor, recipeForProblem } from "@/lib/data/traces";
import type { Difficulty, Language, Trace } from "@/lib/types";

export function TraceWorkbench({
  slug,
  title,
  difficulty,
  patternNames,
  leetcodeUrl,
}: {
  slug: string;
  title: string;
  difficulty: Difficulty;
  patternNames: string[];
  /** Absent for questions with no upstream source. */
  leetcodeUrl?: string | null;
}) {
  const recipe = recipeForProblem(slug);

  const [trace, setTrace] = useState<Trace | undefined>(() => defaultTraceFor(slug));
  const [language, setLanguage] = useState<Language>("JAVA");
  const [codeVisible, setCodeVisible] = useState(true);
  const [configOpen, setConfigOpen] = useState(false);
  const [fields, setFields] = useState<Record<string, string>>(() =>
    Object.fromEntries((recipe?.fields ?? []).map((field) => [field.key, field.value])),
  );
  const [inputError, setInputError] = useState<string | null>(null);

  const codePaneRef = useRef<HTMLDivElement>(null);

  const steps = useMemo(() => trace?.steps ?? [], [trace]);
  const total = steps.length;

  const { cursor, playing, speed, atEnd, setSpeed, goTo, reset, togglePlay, stepBy } =
    usePlayback(total);

  const step = steps[cursor];

  /* --- Keep the active code line in view --------------------------------- */

  useEffect(() => {
    if (!step || !codeVisible) return;
    const pane = codePaneRef.current;
    const row = pane?.querySelector(`#code-line-${step.lineHighlight[language]}`);
    row?.scrollIntoView({ block: "nearest", behavior: "smooth" });
  }, [step, language, codeVisible]);

  /* --- Inputs ------------------------------------------------------------ */

  const applyInputs = () => {
    if (!recipe) return;
    try {
      const next = recipe.build(fields);
      setTrace(next);
      reset();
      setInputError(null);
      setConfigOpen(false);
    } catch (error) {
      setInputError(
        error instanceof TraceInputError ? error.message : "That input could not be traced.",
      );
    }
  };

  const resetInputs = () => {
    if (!recipe) return;
    setFields(Object.fromEntries(recipe.fields.map((field) => [field.key, field.value])));
    setInputError(null);
  };

  if (!trace || !step) {
    return (
      <div className="mx-auto max-w-[560px] px-8 py-24 text-center">
        <Eyebrow className="block">Trace workbench</Eyebrow>
        <h1 className="mt-3 text-[28px]">No trace is authored for {title} yet.</h1>
        <p className="mt-3 text-[14px] leading-relaxed text-ink-2">
          Traces are generated by running the algorithm, so each problem needs a generator
          registered before it can be stepped through.
        </p>
        <div className="mt-6 flex justify-center gap-3">
          <Link href={`/questions/${slug}`} className="link-quiet text-[13px] font-medium">
            Read the approach
          </Link>
        </div>
      </div>
    );
  }

  const codeLines = trace.code[language];
  const activeLine = step.lineHighlight[language];

  return (
    <div className="flex h-[calc(100vh-56px)] min-h-[680px] flex-col">
      {/* Header ------------------------------------------------------------ */}
      <header className="flex flex-wrap items-center justify-between gap-x-6 gap-y-3 border-b border-rule px-6 py-3">
        <div className="flex min-w-0 items-center gap-4">
          <Link
            href={`/questions/${slug}`}
            className="eyebrow shrink-0 transition-colors hover:text-ink"
          >
            ← Question
          </Link>
          <span className="marker-num">/</span>
          <h1 className="truncate text-[19px] leading-none">{title}</h1>
          <span className="hidden items-center gap-2.5 sm:flex">
            {/* Difficulty was hardcoded amber here, which mislabelled every
                easy and hard problem. */}
            <DifficultyTag difficulty={difficulty} className="text-[12px]" />
            <Eyebrow>{patternNames.join(" · ")}</Eyebrow>
          </span>
        </div>

        <div className="flex flex-wrap items-center gap-2">
          <Segmented
            label="Code language"
            value={language}
            onChange={setLanguage}
            options={[
              { value: "JAVA", label: "Java" },
              { value: "PYTHON", label: "Python" },
            ]}
          />

          <Button
            variant={codeVisible ? "outline" : "primary"}
            size="sm"
            onClick={() => setCodeVisible((value) => !value)}
          >
            <Code2 className="size-3.5" strokeWidth={1.7} />
            {codeVisible ? "Hide code" : "Show code"}
          </Button>

          {recipe ? (
            <Button
              variant={configOpen ? "primary" : "outline"}
              size="sm"
              onClick={() => setConfigOpen((value) => !value)}
              aria-expanded={configOpen}
            >
              <Sliders className="size-3.5" strokeWidth={1.7} />
              Configure inputs
            </Button>
          ) : null}

          {leetcodeUrl ? (
            <a
              href={leetcodeUrl}
              target="_blank"
              rel="noreferrer noopener"
              className="link-quiet ml-1 hidden text-[12px] font-medium lg:inline"
            >
              LeetCode ↗
            </a>
          ) : null}
        </div>
      </header>

      {/* Configure inputs -------------------------------------------------- */}
      {configOpen && recipe ? (
        <div className="border-b border-rule bg-paper-sunken px-6 py-5">
          <div className="flex items-baseline justify-between gap-4">
            <div>
              <Eyebrow className="block">Configure inputs</Eyebrow>
              <p className="mt-1.5 max-w-[62ch] text-[13px] text-ink-2">
                The trace is generated by running the algorithm, so any input you enter is traced
                for real — nothing here is pre-recorded.
              </p>
            </div>
            <IconButton label="Close inputs" size="sm" variant="quiet" onClick={() => setConfigOpen(false)}>
              <X className="size-3.5" strokeWidth={1.7} />
            </IconButton>
          </div>

          <div className="mt-4 flex flex-wrap items-end gap-4">
            {recipe.fields.map((field) => (
              <label key={field.key} className="min-w-[300px] flex-1">
                <span className="mb-1.5 block font-mono text-[11px] text-ink-2">{field.label}</span>
                <input
                  value={fields[field.key] ?? ""}
                  placeholder={field.placeholder}
                  onChange={(event) =>
                    setFields((current) => ({ ...current, [field.key]: event.target.value }))
                  }
                  onKeyDown={(event) => {
                    if (event.key === "Enter") applyInputs();
                  }}
                  className="w-full border border-rule bg-card px-3 py-2 font-mono text-[13px] text-ink outline-none focus:border-brand"
                />
                <span className="mt-1.5 block text-[11.5px] text-ink-3">{field.hint}</span>
              </label>
            ))}

            <div className="flex items-center gap-2 pb-6">
              <Button variant="primary" size="md" onClick={applyInputs}>
                Run trace
              </Button>
              <Button variant="quiet" size="md" onClick={resetInputs}>
                Reset
              </Button>
            </div>
          </div>

          {inputError ? (
            <p role="alert" className="mt-1 text-[12.5px] text-danger">
              {inputError}
            </p>
          ) : null}
        </div>
      ) : null}

      {/* Body -------------------------------------------------------------- */}
      <div className="flex min-h-0 flex-1">
        {codeVisible ? (
          <aside className="flex w-[400px] shrink-0 flex-col border-r border-rule">
            <div className="flex items-center justify-between gap-3 border-b border-rule px-4 py-2.5">
              <Eyebrow>Source · {language === "JAVA" ? "Java" : "Python"}</Eyebrow>
              <Eyebrow>Line {activeLine}</Eyebrow>
            </div>
            <div ref={codePaneRef} className="min-h-0 flex-1 overflow-auto py-2">
              <CodeBlock
                lines={codeLines}
                language={language}
                activeLine={activeLine}
                onLineClick={(line) => {
                  // Seek to the first step that touches the clicked line.
                  const target = steps.findIndex((item) => item.lineHighlight[language] === line);
                  if (target >= 0) goTo(target);
                }}
              />
            </div>
            <div className="border-t border-rule px-4 py-2.5">
              <Eyebrow>Click a line to seek</Eyebrow>
            </div>
          </aside>
        ) : null}

        {/* Canvas ---------------------------------------------------------- */}
        <TraceCanvas step={step} total={total} inputLabel={trace.inputLabel} />
      </div>

      {/* Playback ---------------------------------------------------------- */}
      <footer className="border-t border-rule px-6 py-3">
        <div className="flex items-center gap-6">
          <div className="flex items-center gap-1.5">
            <IconButton label="Reset to first step" size="sm" onClick={reset}>
              <RotateCcw className="size-3.5" strokeWidth={1.7} />
            </IconButton>
            <IconButton
              label="Previous step"
              size="sm"
              onClick={() => stepBy(-1)}
              disabled={cursor === 0}
            >
              <ChevronLeft className="size-4" strokeWidth={1.8} />
            </IconButton>
            <Button variant="primary" size="sm" onClick={togglePlay} className="w-[74px]">
              {playing ? (
                <>
                  <Pause className="size-3.5" strokeWidth={2} /> Pause
                </>
              ) : (
                <>
                  <Play className="size-3.5" strokeWidth={2} /> {atEnd ? "Replay" : "Play"}
                </>
              )}
            </Button>
            <IconButton
              label="Next step"
              size="sm"
              onClick={() => stepBy(1)}
              disabled={atEnd}
            >
              <ChevronRight className="size-4" strokeWidth={1.8} />
            </IconButton>
          </div>

          <TraceRuler steps={steps} cursor={cursor} onSeek={goTo} />

          <div className="flex shrink-0 items-center gap-4">
            <Segmented
              label="Playback speed"
              value={String(speed)}
              onChange={(value) => setSpeed(Number(value) as (typeof SPEEDS)[number])}
              options={SPEEDS.map((value) => ({ value: String(value), label: `${value}×` }))}
            />
            <span className="font-mono text-[12px] tabular-nums text-ink-2">
              {String(step.stepIndex).padStart(2, "0")} / {total}
            </span>
          </div>
        </div>

        <div className="mt-2 flex items-center justify-between">
          {/*
           * Describes the ruler ticks by shape and role rather than by colour
           * name. The old wording named the accent directly, which stopped
           * being true the moment the palette changed — and a legend that
           * depends on a token name is a legend that silently goes stale.
           */}
          <Eyebrow>
            Space play · ← → step · R reset · short tick compare · tall tick mutation or return
          </Eyebrow>
          <Eyebrow>Saved locally</Eyebrow>
        </div>
      </footer>
    </div>
  );
}
